# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Kotov
email: kotovalexarian@gmail.com
description: Alex Kotov's personal website.
baseurl: ""
url: "https://kotovalexarian.com"

# Build settings
markdown: kramdown
theme: minima

plugins: []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

font-awesome:
  assets: true

twitter_username:    kotovalexarian
github_username:     kotovalexarian
gitlab_username:     kotovalexarian
bitbucket_username:  kotovalexarian
facebook_username:   kotovalexarian
instagram_username:  kotovalexarian
telegram_username:   kotovalexarian
pocket_username:     kotovalexarian
youtube_channel:     UC5X22dzwK6Gk0mMG66iW4zg
amazon_profile:      amzn1.account.AHABGWEFMHKXJPMN74A2BIFHH3NQ
google_plus_profile: '116990944885097534815'
linkedin_profile:    kotovalexarian
stackoverflow_story: kotovalexarian

pgp_key: |
  -----BEGIN PGP PUBLIC KEY BLOCK-----
  
  mQINBFvZ7ZUBEAC0ovk9Uv6yEX9iUrHVz4hOM15mIn0E59nBsdYkdPdjgcBmFFXc
  Fmouti3q8ekQ09D4lwENxTyBdVo7p/dlo3EZnBsaR9oP6tPQy9V5OEl5Ddy62RCF
  07W3RIxbn59LYCWIf2TfmlUyAlNb/xeqkfTTIwePAUlohxcWnC60AKOK0LCnHDlc
  5VZWzy4rhqqNPC7tSm3uZYhj1Jzc0/qRkwl1+Ux37brYFiVFRuKxxfJUgxI+V22e
  y4j4xb6JiNo+0Ibg6lBGf3gc07Y2kuTvVqI2SGtZycAy6QEVO7eudS3wr6y4iwy8
  33/K+75O71WkMH6DsRlkQdPv77y0S5q7vBa/cdodgem0jESLc7NCnl7R0eZxdDdA
  bE8ezPj9hANk3o7fjKXmkF5lB1SITAzlDimRmRwPLX44kJLz34oyqVYL1zG/U8Bu
  mxtJbUva7Po33zj9uykrMcTX1L+QV6JSAJepNEUX/O9OYIjtLmcAGI96t/JJhZ9v
  EcqAXe5irYKoH0pyHCsmGQo38N14J2rRdPwfdLUU+TVER0WMoPj4HS3pZWFvxzx+
  7ns+zP0XFlZr+aJ6GypXh8pm3ZX8ZNGoL5frpGlVVVil/RjGakhFSJpCbI7O7MDy
  X2Rj9ZfLqbkuZ0ERUFyWPDAX0ELwNZl6UWQyUTrHLhaoSi7uDVjs7enKfQARAQAB
  tCVBbGV4IEtvdG92IDxrb3RvdmFsZXhhcmlhbkBnbWFpbC5jb20+iQJOBBMBCAA4
  FiEEphehc0f3/D2txkyyToMSUPR94VQFAlvZ7ZUCGwMFCwkIBwIGFQgJCgsCBBYC
  AwECHgECF4AACgkQToMSUPR94VTjQQ//V8HreIdcWdPkDVh2uRlpvkbFX7T1Hl87
  sYysHKTQFCziZRlVejTxmE/ulQ+fJ0A4jg6tES6ISkDSuulufUGxoEcHEqWf6aOF
  U7fpVY/3R7iEgm1urFG5FBC+Cw07iKhOSzg1znOLtPdCc79z/kSFuXDCs5dViAsZ
  W2BepXh4lygYvwVFZlVKOT2dzWRhc+ketFPdObIu0f32pfw8pRFvWE2dwbQBE8YF
  eTlHIm77eA1JUBg4cHWMJD0Wt6f6qCrwC1pT5nCWVzZveXc61EPkGn5OWW0VoFuJ
  RbxHXCrkqX0v/XpXi8BK4+G046yuKpGQJWzJAABpCehypH2BG6dwUuUXc/Mixy2/
  PYxTc77iZxMxu3LvnWEI9XEvV/CMU7PqER8RxfjHljpAI5py5TLaPb2cm1Y7g/5W
  IWTeCowI1qKvS2s69eg2AMbQanfWMrIyITPC1dKEkpDSxAaqOP5sxkoBo6si42Ed
  0gMGwNMZgG0U2knjdY2ue5FnTTynbLA5rMV86aF3dHiOpzVPrgWvE6X5MCQcZqBS
  8RMMps07zvw6BzLLUgUdMyLM9UbTB5LxIKSjlvvjmy0VtFsibIkG7NFPnJwiwAoM
  OV8Sl/q63QFDFctC6L/cMS5eWBe2MDOVAOFdo5sfyz6Xycy0gsNrEhFj5ciL+xEt
  r3sENyAAFGi5Ag0EW9ntlQEQAM5otsUlYLhO3ckZzKDq62iqMpiOOjgOzYTBXy41
  Cq2ueiNoQ87RMQcyAa4S4bySRL5OnYsYzDAxYtAnm71hGrzhsg7DT9qvzHzxDwQJ
  mc3AypTYFedwdZwE3jUHBfAjol00Y+bPRb+AAnBxy816FskFN+kfDlHjINppSjOh
  TBl3iYuFX88dc2O15dcNuesJtI62DHo8QPSMIWRjLnOhz83r+T8JqSpxIw8FA/IV
  wxEqL8M546zUo7vtcQW8NZZA+6rxXjMrTfj/1z4b+lsmxiHAUuMf1OHW6mmUkqZ0
  27zy4Ds3AAtSoKogBAU8YBVT2iebgRErUxN/somLlQ5wV8qrp3//mj/Y6bPxqdnq
  Ud8UYYIiIrVB7WPMyJ7fsQEzwjJEdY67U8I5xKcDgXKIbcovOwOW41G+ENt6TiAJ
  sYr6vgogJBmA0y/WcBoFCPRvd3nlKSdITue5mmMl2kcEkr+u+2472idRLU95P8GV
  YCCRjfoDeyomoMmGTq2XCWjpHIViq9lcB1aEn4ZkYExz82JAo1DdLGSiAJxaKvy4
  FMz6qKDhHX1up4aaHhjA/RZzf0dkNy8p1MYIvAmeGB5HWnfe1ipDNh8JZJa05RjQ
  M1N1u3ZQA+lUOAlM1sWNHSGaYRM/wQqOiFvUSxvAOHTlDkTj26kJYkeXvA/B3M9y
  MIrRABEBAAGJAjYEGAEIACAWIQSmF6FzR/f8Pa3GTLJOgxJQ9H3hVAUCW9ntlQIb
  DAAKCRBOgxJQ9H3hVE51EACSJAj9nJmiMv3WwaTifja8nE/MqQ87KI1TumlMgn6v
  3Z4T1Ja1i3Xqky50B2QgBmdK2SuR8L/oC2Qa+QObYk/MQoqV+KB9EM4sQ8KeSBBP
  bFIURck46AFrumXO1E0vatb7k/I/PGZJ7avh2+Ani4reVeHWycMQl5+rFhH9odF3
  DbM5qvbuSZFcxAdRUa9rRKMUFh0pdrWxLrUNc0Q3jUV46qqR1pKjpVs7NfDMA6hd
  HuNvnCMhy8NHrTdR3qY+K26IzLzQd+t7vpYRI2NhIwF3DTrPq3MJ3VgFXPquS/9o
  d6bNRm1n3tDW+ruvcrENqCK7+WlhX3Szs71N4xcm1HYQhfwde8iwACPH5UQE0lTr
  8w3WLgZSahv8A5aM3mcCpstIxh7R3q06KCYgcPU7qdMngBY46zHkH4bi0c4pWmo7
  zSGOdeT/u8+kyCSlgEv4WqtLTtGtOezwqcSGeMoM/a2If0/oUTygVWJKv4fpkRaH
  IHkhY8kuwAver0VaZapmWPLy3XsZnnYiywFGoO77fN+qMQ2q+2IyvcvaVNS6mhEU
  EH2sJFqIN3Zk6fpEUtV5/qAPHnQOkJu2scshm9LgDBrX0QRpxwl+qdZkY/DdNhiN
  rxk36r1GbUB8LlZUT+12aGWlSKeATHGyNImEerHoSxSfHaNQ/D2Sl28vmJ97RB5l
  7Q==
  =7J2f
  -----END PGP PUBLIC KEY BLOCK-----
